# Generated by Django 6.0.1 on 2026-02-01 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mailbody'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarmupControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_gap_seconds', models.IntegerField(default=60)),
                ('daily_limit_per_sender', models.IntegerField(default=10)),
                ('is_running', models.BooleanField(default=False)),
            ],
        ),
    ]
