# Generated by Django 6.0.1 on 2026-02-01 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_warmupcontrol'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailWarmupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mailbody')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recipientmail')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sendermail')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subjectline')),
            ],
        ),
    ]
